[general]
enabled=yes
pretty=yes
allowed_origins=*

[asterisk]
type=user
read_only=no
password=asterisk
password_format=plain

[aziza]
type=user
read_only=no
password=aziza_secure_pass
password_format=plain
