#!/usr/bin/expect -f
set timeout -1

set ssh_host $env(AZIZA_SSH_HOST)
set ssh_pass $env(AZIZA_SSH_PASS)

spawn ssh -o StrictHostKeyChecking=no aziza@$ssh_host
expect "password"
send "$ssh_pass\r"
expect "$ "
send "sudo su -\r"
expect "password"
send "$ssh_pass\r"
expect "# "
send "cd /root/aziza-build\r"
expect "# "
send "cp configs/nginx/aziza.conf /etc/nginx/conf.d/\r"
expect "# "
send "rm -f /etc/nginx/sites-enabled/default\r"
expect "# "
send "nginx -t && systemctl restart nginx\r"
expect "# "
send "exit\r"
expect "$ "
send "exit\r"
expect eof
