#!/usr/bin/expect -f
set timeout -1

set ssh_host $env(AZIZA_SSH_HOST)
set ssh_pass $env(AZIZA_SSH_PASS)

spawn ssh -o StrictHostKeyChecking=no aziza@$ssh_host
expect "password"
send "$ssh_pass\r"

expect {
    "$ " {
        send "sudo su -\r"
        expect "password for aziza:"
        send "$ssh_pass\r"
        expect "# "
    }
    "# " {
    }
}

send "cd /root/aziza-build\r"
expect "# "
send "ls -la\r"
expect "# "
send "tail -n 50 training.log\r"
expect "# "
interact
